"""Freeze recorded gestures for autonomous boot-time Solist-AI training.

This is the final fit, not a new held-out accuracy measurement.
"""
import hashlib
import json
import argparse
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/analysis/2026-09-20-live-calibration/pressure-demo-training.json'
DEST = ROOT / 'src/pneutouch-solist/S_PneuTouch/pressure_model_data.h'


def generate(source=SOURCE):
    data = json.loads(source.read_text(encoding='utf8'))
    events = data['events']
    x = np.array([e['features12'] for e in events], dtype=np.float32)
    count = len(events)
    hidden = data.get('model',{}).get('hidden',32)
    assert hidden in (32,64)
    assert 4 <= count <= 255 and x.shape == (count, 12) and np.isfinite(x).all() and (x > 0).all()
    assert all(e['label'] in (1,2,3,4) for e in events)
    logged = np.log(x.astype(np.float64))
    mean = logged.mean(0).astype(np.float32)
    scale = (3 * logged.std(0)).astype(np.float32)
    # Same float32 operation order as pressure_model.c, then truncate to bf16.
    transformed = (np.log(x) - mean) / scale
    words = transformed.view(np.uint32) >> 16
    rng = np.random.default_rng(1)
    order = np.concatenate([rng.permutation(len(events)) for _ in range(4)])
    def floats(a):
        return ', '.join(f'{float(v):.9e}f' for v in a)
    lines = [
        '/* Generated by tools/generate_pressure_model.py; do not edit. */',
        f'/* {source.name} SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()} */',
        '#ifndef PNEU_MODEL_DATA_H', '#define PNEU_MODEL_DATA_H',
        '#include <stdint.h>', f'#define PNEU_MODEL_EXAMPLES {count}U',
        f'#define PNEU_MODEL_STEPS {count*4}U',
        f'#define PNEU_MODEL_HIDDEN {hidden}U',
        f'static const float model_mean[12] = {{{floats(mean)}}};',
        f'static const float model_scale[12] = {{{floats(scale)}}};',
        f'static const float model_reference_raw[12] = {{{floats(x[0])}}};',
        f'static const uint16_t model_training[{count}][12] = {{'
    ]
    lines += ['    {' + ','.join(f'0x{int(v):04x}' for v in row) + '},' for row in words]
    lines += ['};', f'static const uint8_t model_labels[{count}] = {{' +
              ','.join(str(e['label']) for e in events) + '};',
              f'static const uint8_t model_order[{count*4}] = {{' +
              ','.join(map(str, order)) + '};']
    subset = [e for e in events if e['label'] in (3, 4)]
    sx = np.array([e['features12'] for e in subset], dtype=np.float32)
    sx[:, 5] = np.array([e['peak']/1000 for e in subset], dtype=np.float32)
    slog = np.log(sx.astype(np.float64))
    sm = slog.mean(0).astype(np.float32)
    ss = (3*slog.std(0)).astype(np.float32)
    assert (ss > 1e-8).all() and len(subset) >= 2
    sw = ((np.log(sx)-sm)/ss).view(np.uint32) >> 16
    srng = np.random.default_rng(1)
    so = np.concatenate([srng.permutation(len(subset)) for _ in range(4)])
    lines += ['/* Instance 1: HEAD/LEGS only. Input 5 is positive peak / 1000 counts. */',
              '#define PNEU_SPECIALIST_HIDDEN 32U',
              f'#define PNEU_SPECIALIST_EXAMPLES {len(subset)}U',
              f'#define PNEU_SPECIALIST_STEPS {len(subset)*4}U',
              f'static const float specialist_mean[12] = {{{floats(sm)}}};',
              f'static const float specialist_scale[12] = {{{floats(ss)}}};',
              f'static const float specialist_reference_shape[12] = {{{floats(subset[0]["features12"])}}};',
              f'static const float specialist_reference_peak = {float(subset[0]["peak"]):.9e}f;',
              f'static const uint16_t specialist_training[{len(subset)}][12] = {{']
    lines += ['    {' + ','.join(f'0x{int(v):04x}' for v in row) + '},' for row in sw]
    lines += ['};', f'static const uint8_t specialist_labels[{len(subset)}] = {{' +
              ','.join(str(e['label']) for e in subset) + '};',
              f'static const uint8_t specialist_order[{len(so)}] = {{' +
              ','.join(map(str, so)) + '};', '#endif', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', type=Path, default=SOURCE)
    args = parser.parse_args()
    DEST.write_text(generate(args.input), encoding='utf8')
    print(DEST)
