"""Freeze recorded gestures for autonomous boot-time Solist-AI training.

This is the final fit, not a new held-out accuracy measurement.
"""
import hashlib
import json
import argparse
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/analysis/2026-09-20-live-calibration/pressure-demo-training.json'
DEST = ROOT / 'src/pneutouch-solist/S_PneuTouch/pressure_model_data.h'


def generate(source=SOURCE):
    data = json.loads(source.read_text(encoding='utf8'))
    events = data['events']
    x = np.array([e['features12'] for e in events], dtype=np.float32)
    count = len(events)
    hidden = data.get('model',{}).get('hidden',32)
    assert hidden in (32,64)
    assert 4 <= count <= 255 and x.shape == (count, 12) and np.isfinite(x).all() and (x > 0).all()
    assert all(e['label'] in (1,2,3,4) for e in events)
    logged = np.log(x.astype(np.float64))
    mean = logged.mean(0).astype(np.float32)
    scale = (3 * logged.std(0)).astype(np.float32)
    # Same float32 operation order as pressure_model.c, then truncate to bf16.
    transformed = (np.log(x) - mean) / scale
    words = transformed.view(np.uint32) >> 16
    rng = np.random.default_rng(1)
    order = np.concatenate([rng.permutation(len(events)) for _ in range(4)])
    def floats(a):
        return ', '.join(f'{float(v):.9e}f' for v in a)
    lines = [
        '/* Generated by tools/generate_pressure_model.py; do not edit. */',
        f'/* {source.name} SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()} */',
        '#ifndef PNEU_MODEL_DATA_H', '#define PNEU_MODEL_DATA_H',
        '#include <stdint.h>', f'#define PNEU_MODEL_EXAMPLES {count}U',
        f'#define PNEU_MODEL_STEPS {count*4}U',
        f'#define PNEU_MODEL_HIDDEN {hidden}U',
        f'static const float model_mean[12] = {{{floats(mean)}}};',
        f'static const float model_scale[12] = {{{floats(scale)}}};',
        f'static const float model_reference_raw[12] = {{{floats(x[0])}}};',
        f'static const uint16_t model_training[{count}][12] = {{'
    ]
    lines += ['    {' + ','.join(f'0x{int(v):04x}' for v in row) + '},' for row in words]
    lines += ['};', f'static const uint8_t model_labels[{count}] = {{' +
              ','.join(str(e['label']) for e in events) + '};',
              f'static const uint8_t model_order[{count*4}] = {{' +
              ','.join(map(str, order)) + '};', '#endif', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', type=Path, default=SOURCE)
    args = parser.parse_args()
    DEST.write_text(generate(args.input), encoding='utf8')
    print(DEST)
